Config:
  # 強制重新刷新文件
  Refresh: false
  # 版本號識別用於對舊版本文件設定更新設定節點功能
  Version: "2"
  PlayerDefaultProfile:
    # 技能
    SkillPoint: 0
    SkillResetPoint: 0
    # 職業
    ClassPoint: 0
    ClassReset: 0
    # 技能樹
    SkillTreePoint: 0
    SkillTreeResetPoint: 0
    # 天賦
    TalentPoint: 0
  # 訊息樣板
  Messages:
    # 前綴訊息
    prefix: "<color:#32a852>CGRPGCore <gray>⟫"